// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA13fCkhmyNEH-7u7XdFGRtt-96xHltCZE',
    appId: '1:216645812461:web:0b7a8e4017cb083b464ce4',
    messagingSenderId: '216645812461',
    projectId: 'kolesofortune-c5723',
    authDomain: 'kolesofortune-c5723.firebaseapp.com',
    databaseURL: 'https://kolesofortune-c5723-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kolesofortune-c5723.appspot.com',
    measurementId: 'G-7Q92XGHE7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVXcaamy5DQZyKUsK73nIZGROKMOq525c',
    appId: '1:216645812461:android:968a5a26b757e4f5464ce4',
    messagingSenderId: '216645812461',
    projectId: 'kolesofortune-c5723',
    databaseURL: 'https://kolesofortune-c5723-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kolesofortune-c5723.appspot.com',
  );
}
